### ISSUE TITLE
{% include <local file> %}

### ISSUE THREAD

**Issue by dertuxmalwieder** [catnapgames/NLTemplate#10]
Out of curiosity: Why does NLTemplate require me to specify the full template directory when including files which are in *the same directory* as the including file?

**Comment by catnapgames** [comment]
Hi, it's just easier to implement - I didn't have to do anything special to resolve relative to another (sub-) path.

**Comment by dertuxmalwieder** [comment]
So that's a WONTFIX then? :(

(Random idea: AFAICS it would be enough to concatenate the `const string & name` with the template path if `name` wasn't found initially.)

**Comment by dertuxmalwieder** [comment]
FYI:

https://bitbucket.org/tux_/blogcpp/src/01b0a1d553a77e739fb1123516a16b294eb82651/3rdparty/NLTemplate/NLTemplate.cpp?at=default&fileviewer=file-view-default

Lines 378+ are a quick fix.

**Comment by catnapgames** [comment]
Thanks for the heads up!


Tom
