### ISSUE TITLE
Demo crashes

### ISSUE THREAD

**Issue by beatmax** [catnapgames/NLTemplate#11]
Just cloned on ubuntu 14.04:

$ cd NLTemplate/NLTemplate
$ g++ -Wall -std=c++11 *.cpp -o demo
$ ./demo 
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)

The README says to use:
gcc -Wall -pedantic -o demo -lstdc++ *.cpp

But that doesn't work (the code uses C++11).

Greetings,
Max

**Comment by catnapgames** [comment]
Try running it from the parent dir.

cd NLTemplate/NLTemplate
g++ ...
cd ..
NLTemplate/demo

The program tries to access ./Templates/*

**Comment by catnapgames** [comment]
Updated instructions in README.
