### ISSUE TITLE
Feature wish: {if ...}

### ISSUE THREAD

**Issue by dertuxmalwieder** [catnapgames/NLTemplate#13]
It is currently not quite easy to have a template with optional blocks, e.g. a footer or something. Most work has to be done from inside the wrapper code.

It would be awesome if you found the time to implement some `{if}`/`{endif}` into NLTemplate. Ex.:

    t.set("optionalblock", "foobar");

-->

    {if optionalblock}
    <div>{{ optionalblock }}</div>
    {else}
    <div>Optional block was omitted.</div>
    {endif}

I tried to implement it myself, but I failed to understand where to start, honestly.

Thanks for considering. :-)

**Comment by catnapgames** [comment]
I'd love to extend NLTemplate in such a way but unfortunately don't have enough time at the moment. Sorry. I hope I get a chance to use it & improve it as part of a paid project in the future. Until then, using block.enable() / disable() is the only way to do optional parts.
