### ISSUE TITLE
please add support for files in memory

### ISSUE THREAD

**Issue by dodol** [catnapgames/NLTemplate#7]
It's a suggestion, but what about handling files which are not written on disk but created in memory?
For example, one could create a string:
```c++
std::string memoryFile = "<html><body>\n<h1>{{ text }}</h1>";
```
an then if one could write *Loader* subclass e.g. *LoaderMemoryFile*, which would load entire string, something like this:
```c++
Loader::Result LoaderMemoryFile::load( const string & stringFile ) {
     return { true, stringFile };
}
```

**Comment by catnapgames** [comment]
Added.
